### ISSUE TITLE
没有 kratos.diy.js 哦

### ISSUE THREAD

**Issue by otorain** [MilkiceForks/Kratos#2]
**问题描述**
+ 控制台里边出现
```
GET http://www.mini-geek.com/wp-content/themes/kratos-m/js/kratos.diy.js?ver=2.6 net::ERR_ABORTED 404 (Not Found)
```
+ 原因是js目录下没有这个 kratos.diy.js

**Comment by milkice233** [comment]
嗯呢 上次从上游 merge updates 的时候就发现了这个问题了
本来这个 js 是给用户自定义一些 js 的，不知道为什么上游在某次commit里把这个文件删除了
解决方案很简单 加个空文件即可 不过最近好忙没空折腾

**Comment by otorain** [comment]
了解
